title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
Channel: "in-core"
# version form must be "x.x.x"
INCORE_VERSION: "4.7.0"
PyIncore: "1.14.0"
PyIncore-Viz: "1.8.4"
PyIncore-Data: "1.6.0"