title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
Channel: "in-core"
# version form must be "x.x.x"
INCORE_VERSION: "4.8.1"
PyIncore: "1.15.1rc1"
PyIncore-Viz: "1.9.0rc1"
PyIncore-Data: "0.6.1rc1"
