title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
IN-CORE: "4.7.0" # Version form must be "x.x.x"
PyIncore: "1.14.0"
PyIncore-Viz: "1.8.4"
PyIncore-Data: "1.6.0"
Channel: "in-core"