title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
Channel: "in-core"
# version form must be "x.x.x"
INCORE_VERSION: "5.3.1"
PyIncore: "1.19.0rc1"
PyIncore-Viz: "1.10.1rc1"
PyIncore-Data: "0.6.3rc1"
