title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
Channel: "in-core"
# version form must be "x.x.x"
INCORE_VERSION: "5.1.0"
PyIncore: "1.17.0"
PyIncore-Viz: "1.10.0"
PyIncore-Data: "0.6.2"
