title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
Channel: "in-core/label/rc"
# version form must be "x.x.x"
INCORE_VERSION: "4.8.0"
PyIncore: "1.14.0rc6"
PyIncore-Viz: "1.9.0"
PyIncore-Data: "0.6.1"
