title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
Channel: "in-core"
#Channel: "in-core/label/rc"
# version form must be "x.x.x"
INCORE_VERSION: "5.5.1"
PyIncore: "1.20.1"
PyIncore-Viz: "1.11.0"
PyIncore-Data: "0.7.0"
