title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
Channel: "in-core"
#Channel: "in-core/label/rc"
# version form must be "x.x.x"
INCORE_VERSION: "6.0.0"
PyIncore: "1.21.0"
PyIncore-Viz: "1.11.1"
PyIncore-Data: "0.8.0"
