title: "IN-CORE Lab component version information"
project: "IN-CORE Lab"
author: "Yong Wook Kim"
#Channel: "in-core"
Channel: "in-core/label/rc"
# version form must be "x.x.x"
INCORE_VERSION: "6.1.0"
PyIncore: "1.22.0rc1"
PyIncore-Viz: "1.12.0rc1"
PyIncore-Data: "1.0.0rc1"
